- name: Install monitoring stack
  hosts: localhost

  vars_files: 
  - vars/ingresses.yaml

  tasks:
  - name: Create namespace
    community.kubernetes.k8s:
      kind: Namespace
      name: observability
      
  - name: Install Kube-Prometheus Stack
    community.kubernetes.helm:
      release_name: monitoring
      release_namespace: observability
      chart_ref: kube-prometheus-stack
      chart_repo_url: https://prometheus-community.github.io/helm-charts
      values: "{{ lookup('template','prometheus_helm_values.yaml.j2') | from_yaml }}"

  - name: Add ingress resources
    loop: "{{ ingresses }}"
    k8s:
      namespace: observability
      resource_definition: "{{ lookup('template', 'ingress.yaml.j2' ) }}"