apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{ wp_fqdn }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80